/* Generated By:JavaCC: Do not edit this line. logoConstants.java */
package tp1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface logoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORW = 5;
  /** RegularExpression Id. */
  int BK = 6;
  /** RegularExpression Id. */
  int RT = 7;
  /** RegularExpression Id. */
  int LT = 8;
  /** RegularExpression Id. */
  int PUP = 9;
  /** RegularExpression Id. */
  int PDW = 10;
  /** RegularExpression Id. */
  int ARC = 11;
  /** RegularExpression Id. */
  int CLS = 12;
  /** RegularExpression Id. */
  int REP = 13;
  /** RegularExpression Id. */
  int UNITARY_COMMAND = 14;
  /** RegularExpression Id. */
  int EMPTY_COMMAND = 15;
  /** RegularExpression Id. */
  int TO = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int MAKE = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int NAME = 22;
  /** RegularExpression Id. */
  int COL = 23;
  /** RegularExpression Id. */
  int LSB = 24;
  /** RegularExpression Id. */
  int RSB = 25;
  /** RegularExpression Id. */
  int QUO = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int MULTIPLY = 29;
  /** RegularExpression Id. */
  int DIVIDE = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<FORW>",
    "<BK>",
    "<RT>",
    "<LT>",
    "<PUP>",
    "<PDW>",
    "\"arc\"",
    "<CLS>",
    "\"repeat\"",
    "<UNITARY_COMMAND>",
    "<EMPTY_COMMAND>",
    "\"to\"",
    "\"end\"",
    "\"make\"",
    "<DIGIT>",
    "<LETTER>",
    "<NUM>",
    "<NAME>",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\"!\"",
  };

}
